### ISSUE TITLE
Sometimes full urls don't link completely

### ISSUE THREAD

**Issue by cmsimike** [gongchat/gong#4]
Using this url:
https://en.wikipedia.org/wiki/Mr._Mercedes_(TV_series)

if put into gong, will render an a tag up to the period, missing everything else.

**Comment by david-j-lee** [comment]
I am using https://github.com/markdown-it/markdown-it for the majority of the text parsing. Seems quite a bit of text doesn't get handled correctly. For example, ¯\_(ツ)_/¯  will end up losing his left arm.

**Comment by david-j-lee** [comment]
Switched to https://github.com/markedjs/marked in https://github.com/gongchat/gong/commit/8a11c7fe48f48a792e9586e95dde03a20d8b3be8 and will be included in the next release (0.2.0).

Hopefully, moving libraries will fix some of the issues that were arising with markdown-it.
